### ISSUE TITLE
Missing display attribute in context

### ISSUE THREAD

**Issue by GreatWizard** [novafloss/django-formidable#121]
The missing atribute is `display` which have by default the value 'FORM'.

Possible values are: FORM or TABLE.
- Form set the preview of the form as a form (default)
- Table set the preview of the form in a table (API kind view)

cf: https://github.com/novafloss/formidable-ui/blob/master/mirage/config.js#L687

**Comment by GreatWizard** [comment]
ping @moumoutte @wo0dyn

**Comment by mgu** [comment]
The display attribute has been put in every fields, but this attribute is only usefull in the builder when the form is previewed.
"display" must be renamed "preview_as" and returned by the /accesses endpoint

**Comment by wo0dyn** [comment]
+1 for `preview_as`. LGTM.
