### ISSUE TITLE
Missing documentation about the API

### ISSUE THREAD

**Issue by brunobord** [novafloss/django-formidable#129]
> As a front-end developer  
> I want a documentation about django-formidable API  
> So that I could build a front-end app using this API

This project is at its core a series of API endpoints. None of them is described in the documentation, so you have to dig into the code to guess what's the front-end payload and what's returned. You won't want to do that if you're a JS guy... digging into Python code, won't you?

I think we may try to generate the API specifications. I'm almost sure that DRF does that in a way or another. Or via a swagger file, but I don't know how to import this in the Sphinx documentation.
I'm up to suggestions.

**Comment by GreatWizard** [comment]
As a JS Guy I'm totally in favor for a generating documentation.
It'as always hard to maintains this kind of docs.

I quickly find https://github.com/marcgibbons/django-rest-swagger :)
We should totally give it a try! (or any plugin that you find better)

**Comment by brunobord** [comment]
marked as working. the glitch is that it's invisible on https://django-formidable.readthedocs.io/en/latest/api.html refs #210

**Comment by brunobord** [comment]
done, a long time ago.
