### ISSUE TITLE
count/record queries on every API view

### ISSUE THREAD

**Issue by brunobord** [novafloss/django-formidable#153]
using [django-perf-rec](https://pypi.python.org/pypi/django-perf-rec), for example, we could have metrics on each API view, and eventually improve them using DRF tools to remove duplicate queries, use joins where needed, etc.

**Comment by moumoutte** [comment]
Try to introduce django-perf-rec into django-formidable in order to resolve the #54 issue

get this kind of file

```
TestContextFormEndPoint.test_queryset:
- db: QUERY = u# - PARAMS = (u...#)
- db: QUERY = u# - PARAMS = (#,)
- db: QUERY = u# - PARAMS = (#,)
- db: QUERY = u# - PARAMS = (#,)
- db: QUERY = u# - PARAMS = (#,)
- db: QUERY = u# - PARAMS = (#,)
- db: QUERY = u# - PARAMS = (#,)
- db: QUERY = u# - PARAMS = (#,)
- db: QUERY = u# - PARAMS = (#,)
- db: QUERY = u# - PARAMS = (#,)
```

Any idea why the queryset are not properly write down ?

**Comment by brunobord** [comment]
yup. https://github.com/YPlan/django-perf-rec/issues/50
I've got a quick'n'dirty patch in my local branch.

**Comment by moumoutte** [comment]
many thxs. My 2 cents, we actually are a library, difficult to not be agnostic on the database and use specific postgres database in tests.

**Comment by moumoutte** [comment]
Put the test package in my local env too and seems to works, may be we can push the folders in tests ?

**Comment by moumoutte** [comment]
I'm not fan with this kind of request which actually is a "meta"

I would like to have a list of requests which only one views to cover in order to split out the work and have a the finest track on the current work like #54 for example.

**Comment by brunobord** [comment]
I tend to think otherwise: to be proactive, you need to set monitoring on each entry point, and progressively tackle the eventual overhead you'll detect. We're lucky to have a very limited number of API views, let's take advantage of this.
