### ISSUE TITLE
Deprecate and then remove the Form Presets

### ISSUE THREAD

**Issue by brunobord** [novafloss/django-formidable#249]
### N+1 version

- [x] Deprecate the Form Presets usage,
  - [x] Raise a DeprecationWarning at loading time,
  - [x] Add a deprecation warning in the swagger documentation
  - [x] Add a deprecation warning in the documentation

### N+2 version

- [x] Remove the Presets models and logic
  - [x] ... what shall we do with the demo ``formidable.js`` code?
  - [x] Remove models and thus, all the business logic,
  - [x] Remove from translations,
  - [x] Remove from Swagger definition,
  - [x] ~~Django migration to remove tables~~ handled by #255

**Comment by brunobord** [comment]
Here's the plan:

1. We'll release a 0.15 version with added documentation about deprecations (DRF 3.3 and Presets)
2. We'll then remove support of DRF 3.3 and Presets and make a 0.16 release.

I'm a bit annoyed by the fact that we don't have a MAJOR version to upgrade because we're breaking retro-compatibility, and I'm reluctant to make a 1.0.0 release just to release a 2.0.0 right after with no real improvement / significant change.

what do you think, @wo0dyn ?

**Comment by wo0dyn** [comment]
We messed up a little bit with the versioning here, but what about releasing `1.0.0` instead of `0.16`? Otherwise, I agree with the plan.

**Comment by brunobord** [comment]
That sounds cool.

**Comment by brunobord** [comment]
argh, nope, don't close me...

**Comment by brunobord** [comment]
we still miss the "next step": actually remove support
