### ISSUE TITLE
Mock introducing test failures depending on the order you run the tests

### ISSUE THREAD

**Issue by brunobord** [novafloss/django-formidable#279]
## What happens

simply run:

```
tox -e django18-py27 -- tests.test_forms tests.test_validators
```

and then:

```
tox -e django18-py27 -- tests.test_validators tests.test_forms
```

The first one succeeds, while the second one fails.

## The usual suspect: mock

Digging into the code of the following test that fails:

https://github.com/novafloss/django-formidable/blob/master/demo/tests/test_forms.py#L339-L343

If you put a breakpoint here, and inspect the fields:

```python
>>> form
<DynamicForm bound=True, valid=Unknown, fields=(text-input)>
>>> form.fields
OrderedDict([(u'text-input', <django.forms.fields.CharField object at 0x7f74961bbf90>)])
>>> field = form.fields['text-input']
>>> field.validators
[<Mock name='mock()' id='140138710730320'>
```

My guess is that in the ``test_validators.py`` module, we "hard mock" a property of the ``ValidatorFactory`` class, and then the mock persists in the rest of the test suite.

### Note

It fails in Python3 also:

```
tox -e django18-py35 -- tests.test_validators tests.test_forms
```

**Comment by alexdashkov** [comment]
My bad, I make a PR to fix it
