### ISSUE TITLE
Rename value to label for fields items

### ISSUE THREAD

**Issue by GreatWizard** [novafloss/django-formidable#76]

**Comment by moumoutte** [comment]
You mean to rename "key" to "label" and keep "value" ?

**Comment by GreatWizard** [comment]
value to label :)
key is the real key for this item

**Comment by moumoutte** [comment]
You right! Sorry, my brain is slow at this time !

What do you think about renaming key => value and value => label ?

**Comment by GreatWizard** [comment]
:+1:
