### ISSUE TITLE
Let users choose their assets for JS/l10n/widgets/and so on

### ISSUE THREAD

**Issue by aRkadeFR** [novafloss/django-formidable#78]
Bonjour,

Je fais un ticket un peu en "To Specify" par vos soin.

Je suis interesse par la solution mise en place aussi :+1: 

Si l'on veut sortir formidable en "libre" ou "open source" (a voir le licensing), un utilisateur de formidable aura envie d'utiliser ses propres JS pour gerer les datetime / date / autres fields.

Il serait bon de faire en sorte de rajouter un mechanism pour load les assets/statics via le built-in Django (a minima) ou autre si vous avez mieux:
https://docs.djangoproject.com/en/1.9/topics/forms/media/

Merci

**Comment by moumoutte** [comment]
There is already a way to customize the built fields inside the final form you get.

http://django-formidable.readthedocs.io/en/latest/forms.html#django-form-class.

We can improve the customization by providing a way in order to specify a Media class for the final form. This is what you have in mind ?

**Comment by aRkadeFR** [comment]
I think this works pretty well.

I had in mind a way to customize the media file related to a specific language. You sometimes want to have a "default" .js library, and add a little extension that parametrize the library conerning the language. For instance "lib-fr.js".

@amessinger  or other front end dev will be more able to see the features needed than me :)

**Comment by moumoutte** [comment]
Already possible through the custom django form class attribute.
