### ISSUE TITLE
Valid data for display form

### ISSUE THREAD

**Issue by GreatWizard** [novafloss/django-formidable#80]
Action de validation des data avant de submit un form.
Permet de récupérer les données d'erreurs sur les validations.

# GET api/form/{id}/validate/
Payload: liste de clé valeur des champs

# Return
## Code 204 (NO CONTENT)
Tout va bien c'est valide ! \o/
Pas de contenu

## Code 400
Liste des erreurs du formulaire selon https://github.com/peopledoc/people-kiki/wiki/API-Guidelines#messages-et-code-derreur

```json
{
  "code": "validation_errors",
  "errors": [{
    "field": "name", 
    "code": "missing_field", 
    "message": "The field name is required."
  }, {
    [...]
  }]
}
```

**Comment by moumoutte** [comment]
I've begining the dev on this feature, but I'm wondering how to manage errors from presets ?
Generally presets errors are not target for one fields, but multiple fields. The question is, what do you suggest for non specific field errors ?

**Comment by moumoutte** [comment]
Another question,

Do we really need this   "code": "missing_field",  ? I mean, it's really painful to render it as is, and I don't see  which kind of code we can put for specific field validation or presets validations.

**Comment by moumoutte** [comment]
Question again,

How to handle files just with "get" method ?

**Comment by moumoutte** [comment]
seems good
