### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by wo0dyn** [novafloss/django-formidable#91]

**Comment by moumoutte** [comment]
The publication to the pypi will be done "after" the integration inside a internal project at @peopledoc. In this case, and only in this case, we will able to release the first version of django-formidable.

**Comment by moumoutte** [comment]
Done ! thxs to @wo0dyn :)

**Comment by wo0dyn** [comment]
I think we can close this issue, right?

**Comment by moumoutte** [comment]
Yep :)
